name: Deploy basic html app

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: üì§ Deploy to FTP Server
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # FTP Deploy
      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          # Th∆∞ m·ª•c b·∫°n mu·ªën upload (root repo)
          local-dir: ./

          # Th∆∞ m·ª•c tr√™n server (VD: /public_html)
          server-dir: /

          # T√πy ch·ªçn: delete c√°c file c≈© kh√¥ng c√≤n trong repo
          dangerous-clean-slate: false
